server:
  port: 8091
  tomcat:
    max-threads: 10

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.188.146:8848
    sentinel:
      transport:
        dashboard: localhost:8080  #指定控制台服务地址
        port: 9999 #跟控制台交流端口 , 随意指定一个没使用的端口
  application:
    name: service-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ms_cdyx?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: root

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

product-service: #  调用的是提供者的名称
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #配置规则 随机
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RetryRule #配置规则 重试
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule #配置规则 响应时间权重
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule #配置规则 最空闲连接策略
    ConnectTimeout: 500 #请求连接超时时间
    ReadTimeout: 1000 #请求处理的超时时间
    OkToRetryOnAllOperations: true #对所有请求都进行重试
    MaxAutoRetriesNextServer: 2 #切换实例的重试次数
#开启Feign对sentinel的支持
feign:
  sentinel:
    enabled: true